version: "3.9"

services:
  app:
    image: skylet-discord:dev
    container_name: skylet-discord
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    env_file:
      - .env
